local HEADER_GUARD = "COMPONENT_H"

local function print_typedef(component)
	if component.extern then
		return
	end
	-- io.write("// ", component.storage, "\n")
	io.write("typedef ")
	if component.storage == Storage.Flag then
		io.write("struct {}")
	elseif component.fields ~= nil then
		io.write("struct {\n")
		for key, value in pairs(component.fields) do
			io.write("\t", value, " ", key, ";\n")
		end
		io.write("}")
	elseif component.actual_type then
		io.write(component.actual_type)
	else
		assert(0, "Unknown component type " .. component.class_name)
	end
	io.write(" ", component.class_name, ";\n\n")
end

local function print_component_enum(components)
	io.write("typedef enum {\n")
	for _, value in ipairs(components) do
		io.write("\tCOMPONENT_", string.upper(value.class_name), ",\n")
	end
	io.write("\tCOMPONENT_SIZE,\n")
	io.write("} ComponentType;\n\n")
end

local function append_header_template()
	local inp = assert(io.open("./meta/components/template_component.h", "r"))
	io.write(inp:read("*all"))
	inp:close()
end

local function generate_xmacro(components)
	io.write("#define COMPONENTS \\")

	local formats = {
		[Storage.Dense] = "DENSE(%s, %s, COMPONENT_%s)",
		[Storage.Flag] = "FLAG(%s, %s, COMPONENT_%s)",
	}

	for i, component in ipairs(components) do
		if i > 1 then
			io.write("\\")
		end
		local lower = string.lower(component.class_name)
		local upper = string.upper(component.class_name)
		local name = component.class_name
		local format = formats[component.storage]
		io.write("\n ")
		io.write(string.format(format, name, lower, upper))
	end
	io.write("\n\n")
end

local function generate_bitmap()
	io.write("#define COMPONENTBITMAP_SLOTSIZE 64\n")
	io.write("typedef struct {\n")
	io.write("\tuint64_t bytes[(COMPONENT_SIZE / COMPONENTBITMAP_SLOTSIZE) + 1];\n")
	io.write("} ComponentBitmap;\n")
	io.write("#define COMPONENT_TO_SLOTBIT(component) (1UL << (component & COMPONENTBITMAP_SLOTSIZE))\n")
	io.write("\n")
end

function WriteComponentAdd(component)
	local ret = component.class_name .. "*"
	if component.storage == Storage.Flag then
		ret = "void"
	end
	local fn = string.lower(component.class_name)
	local format = "%s entity_add_%s(struct world* _world, union entity _entity)"
	io.write(string.format(format, ret, fn))
end

function WriteComponentRemove(component)
	local fn = string.lower(component.class_name)
	local format = "void entity_remove_%s(struct world* _world, union entity _entity)"
	io.write(string.format(format, fn))
end

function WriteComponentGet(component)
	local comp = string.lower(component.class_name)
	local format = "#define entity_get_%s(world, entity) entity_get_component(world, entity, %s)"
	io.write(string.format(format, comp, comp))
end

function GenerateHeaders(components, includes, outfile)
	io.output(outfile)

	io.write("// This file has been autogenerated using meta/components/component_header.lua\n")
	io.write("#ifndef ", HEADER_GUARD, "\n")
	io.write("#define ", HEADER_GUARD, "\n\n")

	io.write("#include <stdint.h>\n")
	io.write("#include <stdbool.h>\n")

	for _, include in ipairs(includes) do
		io.write('#include "', include, '"\n')
	end
	io.write("\n")

	for _, value in ipairs(components) do
		print_typedef(value)
	end
	print_component_enum(components)
	append_header_template()
	for _, value in ipairs(components) do
		WriteComponentGet(value)
		io.write(";\n")
		WriteComponentAdd(value)
		io.write(";\n")
		WriteComponentRemove(value)
		io.write(";\n\n")
	end
	generate_xmacro(components)
	generate_bitmap()
	io.write("#endif // ", HEADER_GUARD, "\n")

	io.close()
	io.output(io.stdout)
end
