local function append_source_template()
	local inp = assert(io.open("./meta/components/template_component.c", "r"))
	io.write(inp:read("*all"))
	inp:close()
end

function WriteComponentAddSrc(component)
	local enum = string.upper(component.class_name)
	local field = string.lower(component.class_name)
	local storage = string.upper(component.storage)
	local format = " {\tENTITY_ADD_%s(_world, _entity, %s, COMPONENT_%s); }\n"
	io.write(string.format(format, storage, field, enum))
end

function WriteComponentRemoveSrc(component)
	local enum = string.upper(component.class_name)
	local format = " {\tENTITY_REMOVE(_world, _entity, COMPONENT_%s); }\n"
	io.write(string.format(format, enum))
end

function GenerateSource(components, outfile)
	io.output(outfile)

	io.write("// This file has been autogenerated using meta/components/component_source.lua\n")
	io.write('#include "components.h"\n\n')
	io.write('#include "entity.h"\n\n')
	append_source_template()
	io.write("\n")
	for _, value in ipairs(components) do
		WriteComponentAdd(value)
		WriteComponentAddSrc(value)
		WriteComponentRemove(value)
		WriteComponentRemoveSrc(value)
		io.write("\n")
	end

	io.close()
	io.output(io.stdout)
end
