IS_HEADER = false

function FunctionBegin(return_type, fn_name, ...)
	local args = { ... }
	if not IS_HEADER then
		io.write("inline ")
	end
	local arg_str = table.concat(args, ", ")
	io.write(string.format("%s %s(%s)", return_type, fn_name, arg_str))
	if IS_HEADER then
		io.write(";\n")
	else
		io.write(" {\n")
	end
end

function FunctionEnd()
	if not IS_HEADER then
		io.write("}\n")
	end
end

function HeaderBegin(header_guard)
	IS_HEADER = true
	io.write("// This file has been autogenerated using meta/math/generate.lua\n")
	io.write("#ifndef ", header_guard, "\n")
	io.write("#define ", header_guard, "\n\n")
end

function HeaderEnd(header_guard)
	io.write("#endif //", header_guard, "\n")
end

function SourceBegin(header_file, includes)
	IS_HEADER = false
	io.write("// This file has been autogenerated using meta/math/generate.lua\n")
	io.write('#include "', header_file, '"\n')
	for _, value in ipairs(includes) do
		io.write("#include ", value, "\n")
	end
end

function SourceEnd()
	IS_HEADER = false
end
