// This file has been autogenerated using meta/components/component_header.lua
#ifndef COMPONENT_H
#define COMPONENT_H

#include <stdint.h>
#include <stdbool.h>
#include "linalg.h"
#include "physics.h"
#include "display.h"

typedef struct {} PlayerTag;

typedef struct {} RandomWalk;

typedef struct {
	bool on_ground;
	float gravity;
	Vec2 velocity;
	ColliderId id;
} Rigidbody;

typedef struct {
	int intensity;
} Light;

typedef Vec2 Position;

typedef struct {} Item;

typedef enum {
	COMPONENT_PLAYERTAG,
	COMPONENT_RANDOMWALK,
	COMPONENT_RIGIDBODY,
	COMPONENT_LIGHT,
	COMPONENT_SPRITEID,
	COMPONENT_POSITION,
	COMPONENT_ITEM,
	COMPONENT_SIZE,
} ComponentType;

#define entity_get_component(world, entity, COMPONENT) (\
	entity_is_alive((world), entity) \
	? &(world)->components.COMPONENT[entity.as.index] \
	: &(world)->components.COMPONENT[0] \
)

union entity;
struct world;

#define entity_get_playertag(world, entity) entity_get_component(world, entity, playertag);
void entity_add_playertag(struct world* _world, union entity _entity);
void entity_remove_playertag(struct world* _world, union entity _entity);

#define entity_get_randomwalk(world, entity) entity_get_component(world, entity, randomwalk);
void entity_add_randomwalk(struct world* _world, union entity _entity);
void entity_remove_randomwalk(struct world* _world, union entity _entity);

#define entity_get_rigidbody(world, entity) entity_get_component(world, entity, rigidbody);
Rigidbody *entity_add_rigidbody(struct world* _world, union entity _entity, Rigidbody data);
void entity_remove_rigidbody(struct world* _world, union entity _entity);

#define entity_get_light(world, entity) entity_get_component(world, entity, light);
Light *entity_add_light(struct world* _world, union entity _entity, Light data);
void entity_remove_light(struct world* _world, union entity _entity);

#define entity_get_spriteid(world, entity) entity_get_component(world, entity, spriteid);
SpriteId *entity_add_spriteid(struct world* _world, union entity _entity, SpriteId data);
void entity_remove_spriteid(struct world* _world, union entity _entity);

#define entity_get_position(world, entity) entity_get_component(world, entity, position);
Position *entity_add_position(struct world* _world, union entity _entity, Position data);
void entity_remove_position(struct world* _world, union entity _entity);

#define entity_get_item(world, entity) entity_get_component(world, entity, item);
void entity_add_item(struct world* _world, union entity _entity);
void entity_remove_item(struct world* _world, union entity _entity);

#define COMPONENTS \
 FLAG(PlayerTag, playertag, COMPONENT_PLAYERTAG)\
 FLAG(RandomWalk, randomwalk, COMPONENT_RANDOMWALK)\
 DENSE(Rigidbody, rigidbody, COMPONENT_RIGIDBODY)\
 DENSE(Light, light, COMPONENT_LIGHT)\
 DENSE(SpriteId, spriteid, COMPONENT_SPRITEID)\
 DENSE(Position, position, COMPONENT_POSITION)\
 FLAG(Item, item, COMPONENT_ITEM)

#define COMPONENTBITMAP_SLOTSIZE 64
typedef struct {
	uint64_t bytes[(COMPONENT_SIZE / COMPONENTBITMAP_SLOTSIZE) + 1];
} ComponentBitmap;
#define COMPONENT_TO_SLOTBIT(component) (1ULL << (component % COMPONENTBITMAP_SLOTSIZE))

#endif // COMPONENT_H
