#ifndef CONFIG_H
#define CONFIG_H


#define SCREEN_HEIGHT (64 + 1)
#define SCREEN_WIDTH (64 + 1)
#define SCREEN_SIZE ((SCREEN_WIDTH) * (SCREEN_HEIGHT))

#define TILE_PIXEL_SIZE 4


#define WINDOW_WIDTH (TILE_PIXEL_SIZE * SCREEN_WIDTH)
#define WINDOW_HEIGHT (TILE_PIXEL_SIZE * SCREEN_HEIGHT)

#define WINDOW_SCALE 3
#define TARGET_WINDOW_WIDTH (WINDOW_WIDTH * WINDOW_SCALE)
#define TARGET_WINDOW_HEIGHT (WINDOW_HEIGHT * WINDOW_SCALE)
#define WINDOW_TITLE "VOFI Dig: Slaves of Alderheim"


#define ENTITY_COUNT 512


typedef enum {
	RENDER_LAYER_BACKGROUND,
	RENDER_LAYER_NORMAL,
	RENDER_LAYER_FOREGROUND,

	RENDER_LAYER_SIZE,
} RenderLayer;

#endif //  CONFIG_H
