#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_HEIGHT (16 + 1)
#define SCREEN_WIDTH (16 + 1)
#define SCREEN_SIZE ((SCREEN_WIDTH) * (SCREEN_HEIGHT))

#define TILE_PIXEL_SIZE 16

#define WINDOW_WIDTH (TILE_PIXEL_SIZE * SCREEN_WIDTH)
#define WINDOW_HEIGHT (TILE_PIXEL_SIZE * SCREEN_HEIGHT)

#define WINDOW_SCALE 3
#define TARGET_WINDOW_WIDTH (WINDOW_WIDTH * WINDOW_SCALE)
#define TARGET_WINDOW_HEIGHT (WINDOW_HEIGHT * WINDOW_SCALE)
#define WINDOW_TITLE "VOFI Dig: Slaves of Alderheim"

#endif //  CONFIG_H
