// This file has been autogenerated using math.py
#ifndef LINALG_H
#define LINALG_H

typedef union {
	struct { int x; int y; };
	int v[2];
} Vec2i;

Vec2i vec2i_add(Vec2i a, Vec2i b);
Vec2i vec2i_sub(Vec2i a, Vec2i b);
Vec2i vec2i_scale(Vec2i a, int scale);
int vec2i_dot(Vec2i a, Vec2i b);
int vec2i_lengthsqr(Vec2i vector);

typedef union {
	struct { float x; float y; };
	float v[2];
} Vec2;

Vec2 vec2_add(Vec2 a, Vec2 b);
Vec2 vec2_sub(Vec2 a, Vec2 b);
Vec2 vec2_scale(Vec2 a, float scale);
float vec2_dot(Vec2 a, Vec2 b);
float vec2_lengthsqr(Vec2 vector);


#endif // LINALG_H
