// This file has been autogenerated using math.py
#ifndef LINALG_H
#define LINALG_H

float fast_inv_sqrt(float v);

typedef union {
	struct { int x; int y; };
	int v[2];
} Vec2i;

Vec2i vec2i_add(Vec2i a, Vec2i b);
Vec2i vec2i_sub(Vec2i a, Vec2i b);
Vec2i vec2i_scale(Vec2i a, int scale);
int vec2i_dot(Vec2i a, Vec2i b);
int vec2i_lengthsqr(Vec2i vector);
void vec2i_print(Vec2i vector);
Vec2i vec2i_normalize(Vec2i vector);
Vec2i vec2i_min(Vec2i a, Vec2i b);
Vec2i vec2i_max(Vec2i a, Vec2i b);

typedef union {
	struct { float x; float y; };
	float v[2];
} Vec2;

Vec2 vec2_add(Vec2 a, Vec2 b);
Vec2 vec2_sub(Vec2 a, Vec2 b);
Vec2 vec2_scale(Vec2 a, float scale);
float vec2_dot(Vec2 a, Vec2 b);
float vec2_lengthsqr(Vec2 vector);
void vec2_print(Vec2 vector);
Vec2 vec2_normalize(Vec2 vector);
Vec2 vec2_min(Vec2 a, Vec2 b);
Vec2 vec2_max(Vec2 a, Vec2 b);


#endif // LINALG_H
