// This file has been autogenerated.
#ifndef TEXTURE_REGISTRY
#define TEXTURE_REGISTRY

#define REGISTRY_TEXTURES \
	TEXTURE(FREN, "./assets/textures/fren.png")\
	TEXTURE(MINER_BEARD_0000, "./assets/textures/miner/beard/0000.png")\
	TEXTURE(MINER_BEARD_0001, "./assets/textures/miner/beard/0001.png")\
	TEXTURE(MINER_BEARD_0002, "./assets/textures/miner/beard/0002.png")\
	TEXTURE(MINER_BEARD_0003, "./assets/textures/miner/beard/0003.png")\
	TEXTURE(MINER_BEARD_0004, "./assets/textures/miner/beard/0004.png")\
	TEXTURE(MINER_BEARD_0005, "./assets/textures/miner/beard/0005.png")\
	TEXTURE(MINER_BODY_0000, "./assets/textures/miner/body/0000.png")\
	TEXTURE(MINER_BODY_0001, "./assets/textures/miner/body/0001.png")\
	TEXTURE(MINER_BODY_0002, "./assets/textures/miner/body/0002.png")\
	TEXTURE(MINER_BODY_0003, "./assets/textures/miner/body/0003.png")\
	TEXTURE(MINER_BODY_0004, "./assets/textures/miner/body/0004.png")\
	TEXTURE(MINER_BODY_0005, "./assets/textures/miner/body/0005.png")\
	TEXTURE(MINER_CLOTH_0000, "./assets/textures/miner/cloth/0000.png")\
	TEXTURE(MINER_CLOTH_0001, "./assets/textures/miner/cloth/0001.png")\
	TEXTURE(MINER_CLOTH_0002, "./assets/textures/miner/cloth/0002.png")\
	TEXTURE(MINER_CLOTH_0003, "./assets/textures/miner/cloth/0003.png")\
	TEXTURE(MINER_CLOTH_0004, "./assets/textures/miner/cloth/0004.png")\
	TEXTURE(MINER_CLOTH_0005, "./assets/textures/miner/cloth/0005.png")\
	TEXTURE(MINER_HAT_0000, "./assets/textures/miner/hat/0000.png")\
	TEXTURE(MINER_HAT_0001, "./assets/textures/miner/hat/0001.png")\
	TEXTURE(MINER_HAT_0002, "./assets/textures/miner/hat/0002.png")\
	TEXTURE(MINER_HAT_0003, "./assets/textures/miner/hat/0003.png")\
	TEXTURE(MINER_HAT_0004, "./assets/textures/miner/hat/0004.png")\
	TEXTURE(MINER_HAT_0005, "./assets/textures/miner/hat/0005.png")\
	TEXTURE(TILE_AMETHYST, "./assets/textures/tile/amethyst.png")\
	TEXTURE(TILE_COAL, "./assets/textures/tile/coal.png")\
	TEXTURE(TILE_DIAMOND, "./assets/textures/tile/diamond.png")\
	TEXTURE(TILE_DIRT, "./assets/textures/tile/dirt.png")\
	TEXTURE(TILE_EMERALD, "./assets/textures/tile/emerald.png")\
	TEXTURE(TILE_GRASS, "./assets/textures/tile/grass.png")\
	TEXTURE(TILE_IRON, "./assets/textures/tile/iron.png")\
	TEXTURE(TILE_MOSS, "./assets/textures/tile/moss.png")\
	TEXTURE(TILE_RUBY, "./assets/textures/tile/ruby.png")\
	TEXTURE(TILE_STONE, "./assets/textures/tile/stone.png")\
	TEXTURE(TILE_URANIUM, "./assets/textures/tile/uranium.png")\
	TEXTURE(TILE_WOOD, "./assets/textures/tile/wood.png")\
	TEXTURE(TORCH, "./assets/textures/torch.png")\


typedef enum {
	TEXTURE_NONE,

	#define TEXTURE(id, _) TEXTURE_##id,
	REGISTRY_TEXTURES
	#undef TEXTURE

	TEXTURE_SIZE,
} TextureId;

#endif // TEXTURE_REGISTRY
