// This file has been autogenerated using math.py
#include "linalg.h"

inline Vec2i vec2i_add(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = a.x + b.x,
		.y = a.y + b.y,
	});
}
inline Vec2i vec2i_sub(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = a.x - b.x,
		.y = a.y - b.y,
	});
}
inline Vec2i vec2i_scale(Vec2i a, int scale) {
	return ((Vec2i){
		.x = a.x * scale,
		.y = a.y * scale,
	});
}
inline int vec2i_dot(Vec2i a, Vec2i b) {
	return (a.x * b.x) + (a.y * b.y);
}
inline int vec2i_lengthsqr(Vec2i vector) {
	return (vector.x * vector.x) + (vector.y * vector.y);
}

inline Vec2 vec2_add(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = a.x + b.x,
		.y = a.y + b.y,
	});
}
inline Vec2 vec2_sub(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = a.x - b.x,
		.y = a.y - b.y,
	});
}
inline Vec2 vec2_scale(Vec2 a, float scale) {
	return ((Vec2){
		.x = a.x * scale,
		.y = a.y * scale,
	});
}
inline float vec2_dot(Vec2 a, Vec2 b) {
	return (a.x * b.x) + (a.y * b.y);
}
inline float vec2_lengthsqr(Vec2 vector) {
	return (vector.x * vector.x) + (vector.y * vector.y);
}


