// This file has been autogenerated using math.py
#include "linalg.h"
#include <stdio.h>
#define min(a, b) (a < b) ? a : b
#define max(a, b) (a > b) ? a : b


inline float fast_inv_sqrt(float v) {
	float vhalf = 0.5f * v;
	int i = *(int*)&v;
	i = 0x5f3759df - (i >> 1);
	v = *(float*)&i;
	v = v * (1.5f - vhalf * v * v);
	return v;
}

inline Vec2i vec2i_add(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = a.x + b.x,
		.y = a.y + b.y,
	});
}
inline Vec2i vec2i_sub(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = a.x - b.x,
		.y = a.y - b.y,
	});
}
inline Vec2i vec2i_scale(Vec2i a, int scale) {
	return ((Vec2i){
		.x = a.x * scale,
		.y = a.y * scale,
	});
}
inline int vec2i_dot(Vec2i a, Vec2i b) {
	return (a.x * b.x) + (a.y * b.y);
}
inline int vec2i_lengthsqr(Vec2i vector) {
	return (vector.x * vector.x) + (vector.y * vector.y);
}
inline void vec2i_print(Vec2i vector) {
	printf("Vec2i(%d, %d)", vector.x, vector.y);
}
inline Vec2i vec2i_normalize(Vec2i vector) {
	float inv_len = fast_inv_sqrt(vec2i_lengthsqr(vector));
	return ((Vec2i){
		.x = (int)(vector.x * inv_len),
		.y = (int)(vector.y * inv_len),
	});
}
inline Vec2i vec2i_min(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = min(a.x, b.x),
		.y = min(a.y, b.y),
	});
}
inline Vec2i vec2i_max(Vec2i a, Vec2i b) {
	return ((Vec2i){
		.x = max(a.x, b.x),
		.y = max(a.y, b.y),
	});
}

inline Vec2 vec2_add(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = a.x + b.x,
		.y = a.y + b.y,
	});
}
inline Vec2 vec2_sub(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = a.x - b.x,
		.y = a.y - b.y,
	});
}
inline Vec2 vec2_scale(Vec2 a, float scale) {
	return ((Vec2){
		.x = a.x * scale,
		.y = a.y * scale,
	});
}
inline float vec2_dot(Vec2 a, Vec2 b) {
	return (a.x * b.x) + (a.y * b.y);
}
inline float vec2_lengthsqr(Vec2 vector) {
	return (vector.x * vector.x) + (vector.y * vector.y);
}
inline void vec2_print(Vec2 vector) {
	printf("Vec2(%f, %f)", vector.x, vector.y);
}
inline Vec2 vec2_normalize(Vec2 vector) {
	float inv_len = fast_inv_sqrt(vec2_lengthsqr(vector));
	return ((Vec2){
		.x = (float)(vector.x * inv_len),
		.y = (float)(vector.y * inv_len),
	});
}
inline Vec2 vec2_min(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = min(a.x, b.x),
		.y = min(a.y, b.y),
	});
}
inline Vec2 vec2_max(Vec2 a, Vec2 b) {
	return ((Vec2){
		.x = max(a.x, b.x),
		.y = max(a.y, b.y),
	});
}


