// This file has been autogenerated.
#include "tile.h"

TileData tile_data[TILE_SIZE] = {
	[TILE_BEDROCK] = {
		.texture = TEXTURE_NONE,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE | TILE_FLAG_UNBREAKABLE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_AIR] = {
		.texture = TEXTURE_TILE_STONE,
		.hardness = 16,
		.flags = 0,
		.layer = RENDER_LAYER_BACKGROUND,
	},
	[TILE_DIRT] = {
		.texture = TEXTURE_TILE_DIRT,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_GRASS] = {
		.texture = TEXTURE_TILE_GRASS,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_MOSS] = {
		.texture = TEXTURE_TILE_MOSS,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_STONE] = {
		.texture = TEXTURE_TILE_STONE,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_WOOD] = {
		.texture = TEXTURE_TILE_WOOD,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_IRON] = {
		.texture = TEXTURE_TILE_IRON,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_DIAMOND] = {
		.texture = TEXTURE_TILE_DIAMOND,
		.hardness = 200,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_COAL] = {
		.texture = TEXTURE_TILE_COAL,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_URANIUM] = {
		.texture = TEXTURE_TILE_URANIUM,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_RUBY] = {
		.texture = TEXTURE_TILE_RUBY,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_EMERALD] = {
		.texture = TEXTURE_TILE_EMERALD,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
	[TILE_AMETHYST] = {
		.texture = TEXTURE_TILE_AMETHYST,
		.hardness = 16,
		.flags = TILE_FLAG_SOLID | TILE_FLAG_OPAQUE,
		.layer = RENDER_LAYER_NORMAL,
	},
};
